builds:
- goos:
  - darwin
  - windows
  - linux
  goarch:
  - amd64
  binary: terracreds
archives:
- name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format_overrides:
    - goos: windows
      format: zip
- files:
  - none*