name: Windows Build

on:
  pull_request:
    branches:
    - main

jobs:
  test-win:
    name: Build and Test Windows
    runs-on: windows-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.19
      id: go
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: |
        New-Item -ItemType Directory -Name terraform.d -Path $env:APPDATA
        $env:HOME=$env:APPDATA
        $env:TC_CONFIG_PATH=$env:APPDATA
        go build .
    - name: Test
      run: |
        $env:PATH += ";$pwd"
        cd cmd
        go test -v -cover